name: Run Code

on:
  push:
    branches:
        - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    container: python:3.11
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: show files
        run: |
          echo "Hello, CI with GitHub Actions!."
