name: task2

on:
  push:
    branches:
        - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then
            python -m pip install --upgrade pip
            pip install --no-cache-dir -r requirements.txt
          else
            echo "No requirements.txt found, skipping."
          fi

      - name: Run unit tests
        run: |
          python -m unittest discover -s tests -p "test_*.py" -v

      - name: finish
        run: |
          echo "Finished successfully!"    
