name: task2

on:
  push:
    branches:
        - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    container: python:3.9
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
          pip install -r requirements.txt

      - name: finish
        run: |
          echo "Finished successfully!"    
