name: task4

on:
  push:
    branches:
        - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python: ['3.8', '3.9', '3.10']
        include:
          - os: ubuntu-22.04
            python: '3.7'   # only this combo gets 3.7
            
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
          
      - name: Run unit tests
        run: |
          python -m unittest discover -s tests -p "test_*.py" -v

      - name: finish
        run: |
          echo "Finished successfully! Python ${{ matrix.python }} on ${{ runner.os }}"    
